trigger:
  branches:
    include:
      - main

parameters:
  - name: fruit
    displayName: Select fruit (software version)
    type: string
    values:
      - apple
      - banana
      - cherry

  - name: vm
    displayName: Select target VM
    type: string
    values:
      - VM0
      - VM1
      - VM2
      - VM4
      - VM5
      - VM6

pool:
  vmImage: 'windows-latest'

steps:
  - script: |
      echo "Selected fruit: $(fruit)"
      echo "Selected VM: $(vm)"
    displayName: 'Show Inputs'

  - script: echo "✅ Valid Apple VM: $(vm)"
    displayName: 'Apple VM Deploy'
    condition: and(eq(variables['fruit'], 'apple'), or(eq(variables['vm'], 'VM0'), eq(variables['vm'], 'VM1')))

  - script: echo "✅ Valid Banana VM: $(vm)"
    displayName: 'Banana VM Deploy'
    condition: and(eq(variables['fruit'], 'banana'), or(eq(variables['vm'], 'VM2'), eq(variables['vm'], 'VM4')))

  - script: echo "✅ Valid Cherry VM: $(vm)"
    displayName: 'Cherry VM Deploy'
    condition: and(eq(variables['fruit'], 'cherry'), or(eq(variables['vm'], 'VM5'), eq(variables['vm'], 'VM6')))

  - script: |
      echo "❌ Invalid fruit/VM combination"
      exit 1
    displayName: 'Invalid Selection'
    condition: not(
      or(
        and(eq(variables['fruit'], 'apple'), or(eq(variables['vm'], 'VM0'), eq(variables['vm'], 'VM1'))),
        and(eq(variables['fruit'], 'banana'), or(eq(variables['vm'], 'VM2'), eq(variables['vm'], 'VM4'))),
        and(eq(variables['fruit'], 'cherry'), or(eq(variables['vm'], 'VM5'), eq(variables['vm'], 'VM6')))
      )
    )
