trigger:
  branches:
    include:
      - main

parameters:
  - name: fruit
    displayName: Select fruit (software version)
    type: string
    values:
      - apple
      - banana
      - cherry

  - name: vm
    displayName: Select target VM
    type: string
    values:
      - VM0
      - VM1
      - VM2
      - VM4
      - VM5
      - VM6

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    echo "Selected fruit: ${{ parameters.fruit }}"
    echo "Selected VM: ${{ parameters.vm }}"
  displayName: 'Show Inputs'

- ${{ if and(eq(parameters.fruit, 'apple'), or(eq(parameters.vm, 'VM0'), eq(parameters.vm, 'VM1'))) }}:
  - script: echo "✅ Valid Apple VM: ${{ parameters.vm }}"
    displayName: 'Apple VM Deploy'

- ${{ if and(eq(parameters.fruit, 'banana'), or(eq(parameters.vm, 'VM2'), eq(parameters.vm, 'VM4'))) }}:
  - script: echo "✅ Valid Banana VM: ${{ parameters.vm }}"
    displayName: 'Banana VM Deploy'

- ${{ if and(eq(parameters.fruit, 'cherry'), or(eq(parameters.vm, 'VM5'), eq(parameters.vm, 'VM6'))) }}:
  - script: echo "✅ Valid Cherry VM: ${{ parameters.vm }}"
    displayName: 'Cherry VM Deploy'

- ${{ if not(
      or(
        and(eq(parameters.fruit, 'apple'), or(eq(parameters.vm, 'VM0'), eq(parameters.vm, 'VM1'))),
        and(eq(parameters.fruit, 'banana'), or(eq(parameters.vm, 'VM2'), eq(parameters.vm, 'VM4'))),
        and(eq(parameters.fruit, 'cherry'), or(eq(parameters.vm, 'VM5'), eq(parameters.vm, 'VM6')))
      )
  ) }}:
  - script: |
      echo "❌ Invalid fruit/VM combination"
      exit 1
    displayName: 'Invalid Selection'
